{% set version = "1.2.5" %}

package:
  name: gpi
  version: {{ version }}

source:
  url: https://github.com/gpilab/framework/archive/v{{ version }}.tar.gz
  sha256: cc0a813f8494f0792797209153b8ba2162add6fe74480db994ffb8e67c8ce232

build:
  noarch: python
  number: 0
  skip_compile_pyc:
    - include/PyFI/*.py

requirements:
  host:
    - python >=3
  run:
    - python >=3
    - eigen
    - fftw
    - h5py
    - numpy >=1.11,<2
    - pillow
    - psutil
    - pyopengl
    - pyqt >=5.6,<5.13.0a0
    - qtpy
    - sip
    - qimage2ndarray

test:
  requires:
    - xorg-libsm
    - xorg-libxcb
    - xorg-libxrender
  imports:
    - gpi
  commands:
    - DISPLAY=localhost:1.0 xvfb-run -a bash -c "gpi --help"
  downstreams:
    - gpi_core

app:
  entry: gpi
  icon: iclogo.png
  summary: Graphical Programming Interface
  own_environment: true

about:
  home: http://gpilab.com
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: GPI - Graphical Programming Interface Development Framework
  description: |
    GPI can be thought of as an integrated development environment for Python. 
    Algorithm elements (i.e., nodes) can be linked together to form a flow diagram
    that is then executed according to the diagram hierarchy. At the node level,
    the common API and UI elements allow other developers to easily integrate 
    and use your code. The visual and modular nature of GPI also allows concise
    communication of your work with your collaborators and provides an intuitive
    mechanism for others to start interacting with your research.
  doc_url: http://gpilab.com/documentation
  dev_url: https://github.com/gpilab/framework

extra:
  recipe-maintainers:
    - borupdaniel
    - aganders3
