{% set version = "1.1.6" %}

package:
  name: gpi
  version: {{ version }}

source:
  url: https://github.com/gpilab/framework/archive/v{{ version }}.tar.gz
  sha256: 8a0cfa3b0b70935d35be33f83aa0b6383fd04a72eee50b7c54a0a5f29a8b9487

build:
  noarch: python
  number: 0
  skip_compile_pyc:
    - "include/PyFI/*.py"

requirements:
  host:
    - python >=3
  run:
    - python >=3
    - eigen
    - fftw
    - h5py
    - numpy >=1.11,<2
    - pillow
    - psutil
    - pyopengl
    - pyqt >=5.6,<=5.9
    - qtpy
    - sip
    - qimage2ndarray

test:
  imports:
    - gpi
  commands:
    - DISPLAY=localhost:1.0 xvfb-run -a bash -c "gpi --help"  # [linux]
    - gpi --help  # [osx]
  downstreams:
    - gpi_core

about:
  home: http://gpilab.com
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: "GPI - Graphical Programming Interface Development Framework"
  description: |
    GPI can be thought of as an integrated development environment for Python. 
    Algorithm elements (i.e., nodes) can be linked together to form a flow diagram
    that is then executed according to the diagram hierarchy. At the node level,
    the common API and UI elements allow other developers to easily integrate 
    and use your code. The visual and modular nature of GPI also allows concise
    communication of your work with your collaborators and provides an intuitive
    mechanism for others to start interacting with your research.
  doc_url: http://gpilab.com/documentation
  dev_url: https://github.com/gpilab/framework

extra:
  recipe-maintainers:
    - borupdaniel
    - aganders3
